theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 40

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
<<<<<<< HEAD
device = "enp0s25"
=======
device = "wlan0"
>>>>>>> c35a5d6 (Added battery/network status show in i3)
interval = 3

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
