#!/bin/bash

# Go to user's home directory
cd "$HOME"

echo "yadm bootrapping.."
echo ""
echo ""

echo "Update submodules.."
yadm submodule update --recursive --init

echo "Install Emacs config.."
# Install Emacs
git clone https://github.com/qoor/.emacs.d ~/.emacs.d

# Install neovim plugins
mkdir -pv ~/.local/share/nvim/site/autoload
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

echo "Install neovim plugins.."
nvim -c 'PlugInstall' -c 'qa!'

echo ""
echo ""
echo "yadm bootstrap complete!"
